-- ⚠️ SECURITY NOTICE: Legacy views were removed
-- 
-- The archived_legacy_orders and archived_legacy_simple_orders views were 
-- removed because they created security vulnerabilities by using SECURITY DEFINER.
--
-- If you need read-only historical access to this data, you should:
-- 1. Query the tables directly (orders, simple_orders) with proper authentication
-- 2. Use the unified views (v_orders_unified, v_order_items_unified) which now use 
--    SECURITY INVOKER and respect RLS policies
-- 3. Create specific RLS policies for any read-only access requirements
--
-- The frontend and server code rely exclusively on ecommerce_* tables and the 
-- unified views for data access.
